name: Formatting

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

env:
  CARGO_TERM_COLOR: always

jobs:
  check-rs-format:
    name: Check Formatting (Rust)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@master
        with:
          components: rustfmt
          toolchain: nightly
      - name: rustfmt
        run: cargo fmt --check

  check-prettier-format:
    name: Check Formatting (Prettier)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Check formatting with Prettier
        uses: actionsx/prettier@v3
        with:
          args: -c .
